image: atlassian/default-image:4

definitions:
  release:
    - step: &build
        name: Build
        script:
          - VERSION="b.$BITBUCKET_BUILD_NUMBER"
          - IMAGE="$DOCKERHUB_USERNAME/$BITBUCKET_REPO_SLUG"
          - docker image build --platform linux/arm64,linux/amd64 -t ${IMAGE}:${VERSION} .
          - docker image push ${IMAGE}:${VERSION}
        services:
          - docker
        output-variables:
          - VERSION
          - IMAGE
    - step: &test
        name: tests
        script:
          - ./tests/docker.sh ${IMAGE}:${VERSION}
        services:
          - docker
    - step: &release
        name: release
        deployment: production
        script:
          # Build and push image
          - pip3 install yq
          - RELEASE_VERSION=$(yq -r '.version' pipe.yml)
          - docker image tag ${IMAGE}:${VERSION} ${IMAGE}:latest ${IMAGE}:${RELEASE_VERSION}
          - docker image push ${IMAGE}:latest ${IMAGE}:${RELEASE_VERSION}
          # Push tags
          - git tag -a "${RELEASE_VERSION}" -m "Tagging for release ${VERSION}"
          - git push origin ${RELEASE_VERSION}
        services:
          - docker
        output-variables:
          - RELEASE_VERSION
    - step: &checkIfReleaseExists
        name: Check if release exists
        script:
          - pip3 install yq
          - RELEASE_VERSION=$(yq -r '.version' pipe.yml)
          - if git tag -l | grep -q "${RELEASE_VERSION}"; then
            echo "Release ${RELEASE_VERSION} already exists. Skipping release step.";
            exit 0;
            else
            echo "No existing release found. Proceeding with release.";
            fi

  develop:
    - step: *build
    - step: *test

pipelines:
  branches:
    develop:
      - step: *build
      - step: *test
    main:
      - step: *checkIfReleaseExists
      - step: *build
      - step: *test
      - step: *release
